### PR TITLE
refactor: remove android module and replace by JS stub

### PR DESCRIPTION
**Pull request by pke**
We do not need the android module to just return `false`. We can do that in JS by using platform specific JS files.

### CODE REVIEW

**Comment by pke** [comment]
@dejan9393 could you please take a look and merge if your time permits? Thanks!

**Comment by swushi** [comment]
+1

**Comment by pke** [comment]
@dejan9393 thanks! Could you also release a new version to npm please?

**Comment by dejan9393** [comment]
@pke Sure, that's now published! Thanks for the patch - apologies for the delay!

**Comment by pke** [comment]
You may want to remove the Android instructions from the README too, forgot about those.

**Pull request merged**
